// Dummy data for teams
export const featuredTeams = [
  {
    id: "1",
    name: "ONIC Esports",
    logo: "/logo/ONIC.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: [
      "MPL ID S11 Champion",
      "M4 World Championship Runner-up",
      "MPL ID S10 Champion",
    ],
    players: 5,
    matches: 245,
    winRate: 68,
  },
  {
    id: "2",
    name: "RRQ Hoshi",
    logo: "/logo/RRQ.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: [
      "MPL ID S9 Champion",
      "MPL ID S8 Champion",
      "M3 World Championship 3rd Place",
    ],
    players: 6,
    matches: 256,
    winRate: 65,
  },
  {
    id: "3",
    name: "Blacklist International",
    logo: "/logo/BLACK.jpg",
    country: "Philippines",
    region: "SEA",
    achievements: [
      "M3 World Champion",
      "MPL PH S7 Champion",
      "MPL PH S8 Champion",
    ],
    players: 5,
    matches: 230,
    winRate: 72,
  },
  {
    id: "4",
    name: "ECHO",
    logo: "/logo/ECHO.jpg",
    country: "Philippines",
    region: "SEA",
    achievements: ["M4 World Champion", "MPL PH S10 Champion"],
    players: 5,
    matches: 210,
    winRate: 70,
  },
];

export const allTeams = [
  ...featuredTeams,
  {
    id: "5",
    name: "EVOS Legends",
    logo: "/logo/EVOS.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: ["MPL ID S4 Champion", "M1 World Champion"],
    players: 6,
    matches: 235,
    winRate: 62,
  },
  {
    id: "6",
    name: "Alter Ego",
    logo: "/logo/ALTER.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: ["MPL ID S6 Runner-up", "ONE Esports MPLI 2020 Runner-up"],
    players: 5,
    matches: 220,
    winRate: 60,
  },
  {
    id: "7",
    name: "Geek Fam ID",
    logo: "/logo/GEEK.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: ["MPL ID S5 Champion"],
    players: 5,
    matches: 200,
    winRate: 58,
  },
  {
    id: "8",
    name: "Aura Fire",
    logo: "/logo/AURA.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: ["MPL ID S7 3rd Place", "MPL ID S8 3rd Place"],
    players: 6,
    matches: 215,
    winRate: 59,
  },
  {
    id: "9",
    name: "Bigetron Alpha",
    logo: "/logo/BIGETRON.jpg",
    country: "Indonesia",
    region: "SEA",
    achievements: ["MPL ID S9 3rd Place"],
    players: 5,
    matches: 190,
    winRate: 56,
  },
  {
    id: "10",
    name: "Team SMG",
    logo: "/logo/SMG.jpg",
    country: "Malaysia",
    region: "SEA",
    achievements: ["MPL MY S9 Champion", "MPL MY S8 Champion"],
    players: 5,
    matches: 180,
    winRate: 63,
  },
  {
    id: "11",
    name: "Todak",
    logo: "/logo/TODAK.jpg",
    country: "Malaysia",
    region: "SEA",
    achievements: ["MPL MY S7 Champion", "M3 World Championship 5th-6th Place"],
    players: 5,
    matches: 175,
    winRate: 61,
  },
  {
    id: "12",
    name: "Falcon Esports",
    logo: "/logo/FALCON.jpg",
    country: "Myanmar",
    region: "SEA",
    achievements: ["M4 World Championship 3rd-4th Place"],
    players: 5,
    matches: 150,
    winRate: 65,
  },
];

export const regions = [
  { id: "1", name: "Southeast Asia (SEA)", count: 45 },
  { id: "2", name: "North America", count: 12 },
  { id: "3", name: "Latin America", count: 8 },
  { id: "4", name: "Europe", count: 10 },
  { id: "5", name: "Middle East", count: 6 },
];

export const countries = [
  { id: "1", name: "Indonesia", count: 15 },
  { id: "2", name: "Philippines", count: 12 },
  { id: "3", name: "Malaysia", count: 8 },
  { id: "4", name: "Singapore", count: 4 },
  { id: "5", name: "Myanmar", count: 3 },
  { id: "6", name: "Brazil", count: 5 },
  { id: "7", name: "USA", count: 6 },
];