// import {ReactNode, ReactElement} from 'react'
"use client"
import "@/styles/globals.css"

// import {Inter} from 'next/font/google'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// const inter = Inter({subsets:['cyrillic-ext','greek','latin','vietnamese']})

// export default function AuthLayout({children}: {children: ReactNode}): ReactElement {
//   return (
//     <html lang='en' className={inter.className}>
//       <body className="container mx-auto px-4">
//         <main className="container mx-auto py-12 max-w-5xl">{children}</main>
//       </body>
//     </html>
//   )
// }

import { useEffect, useState } from "react"
import { usePathname } from "next/navigation"
import Image from "next/image"
import Link from "next/link"
import anime from "animejs"

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  const [mounted, setMounted] = useState(false)
  const isLoginPage = pathname === "/account/login"
  const isRegisterPage = pathname === "/account/register"
  const isAuthLanding = pathname === "/account"

  useEffect(() => {
    setMounted(true)
    
    // Animation for the background gradient
    anime({
      targets: '.gradient-bg',
      backgroundPosition: ['0% 0%', '100% 100%'],
      easing: 'easeInOutQuad',
      duration: 10000,
      loop: true,
      direction: 'alternate'
    })

    // Animation for the card
    if (mounted) {
      anime({
        targets: '.auth-card',
        opacity: [0, 1],
        translateY: [20, 0],
        easing: 'easeOutExpo',
        duration: 800,
        delay: 300
      })
    }
  }, [mounted, pathname])

  return (
    <html>
      <body>
        <div className="relative flex min-h-screen w-full items-center justify-center overflow-hidden">
      {/* Animated gradient background */}
      <div 
        className="gradient-bg absolute inset-0 bg-gradient-to-br from-blue-600/20 via-purple-600/20 to-pink-600/20 bg-[length:200%_200%]"
        style={{ backgroundSize: '200% 200%' }}
      />
      
      {/* Glass effect overlay */}
      <div className="absolute inset-0 backdrop-blur-[2px]" />
      
      {/* Animated shapes */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
        <div className="absolute top-[10%] left-[15%] w-64 h-64 rounded-full bg-blue-500/10 animate-blob" />
        <div className="absolute top-[40%] right-[15%] w-72 h-72 rounded-full bg-purple-500/10 animate-blob animation-delay-2000" />
        <div className="absolute bottom-[10%] left-[35%] w-80 h-80 rounded-full bg-pink-500/10 animate-blob animation-delay-4000" />
      </div>
      
      {/* Content */}
      <div className="auth-card relative z-10 w-full max-w-5xl mx-auto flex rounded-2xl shadow-2xl bg-white/80 dark:bg-slate-900/80 backdrop-blur-md overflow-hidden h-[80vh]">
        {/* Left side - Branding */}
        <div className="hidden lg:flex lg:w-1/2 relative overflow-hidden bg-gradient-to-br from-blue-600 to-purple-700">
          <div className="absolute inset-0 bg-pattern opacity-10" />
          <div className="relative z-10 flex flex-col justify-between h-full p-12 text-white">
            <div>
              <div className="flex items-center gap-2">
                <div className="h-10 w-10 rounded-lg bg-white flex items-center justify-center">
                  <span className="text-blue-600 font-bold">ML</span>
                </div>
                <span className="font-bold text-2xl">MLAnalysis</span>
              </div>
              <h2 className="mt-12 text-3xl font-bold">Analisis Mobile Legends Profesional</h2>
              <p className="mt-4 text-white/80">
                Platform analisis pertandingan Mobile Legends terlengkap untuk pemain dan tim esports profesional.
              </p>
            </div>
            
            <div className="space-y-6">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-full bg-white/20 flex items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                    <polyline points="22 4 12 14.01 9 11.01"></polyline>
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold">Analisis Pertandingan</h3>
                  <p className="text-sm text-white/70">Analisis mendalam untuk setiap pertandingan</p>
                </div>
              </div>
              
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-full bg-white/20 flex items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
                    <path d="M2 17l10 5 10-5"></path>
                    <path d="M2 12l10 5 10-5"></path>
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold">Statistik Tim & Pemain</h3>
                  <p className="text-sm text-white/70">Data statistik lengkap untuk semua tim</p>
                </div>
              </div>
              
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-full bg-white/20 flex items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <polyline points="12 6 12 12 16 14"></polyline>
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold">Turnamen Terkini</h3>
                  <p className="text-sm text-white/70">Informasi turnamen dari seluruh dunia</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        {/* Right side - Auth content */}
        <div className="w-full lg:w-1/2 p-8 flex items-center bg-gray-100 justify-center">
          {isAuthLanding ? (
            <div className="w-full max-w-md space-y-8 auth-landing">
              <div className="text-center">
                <h1 className="text-3xl font-bold tracking-tight">Selamat Datang</h1>
                <p className="mt-2 text-muted-foreground">
                  Pilih opsi di bawah untuk melanjutkan
                </p>
              </div>
              
              <div className="space-y-4 mt-8">
                <Link href="/account/login" className="auth-option-card block p-6 rounded-xl border border-blue-200 bg-blue-50 hover:shadow-md transition-all hover:-translate-y-1">
                  <div className="flex items-center gap-4">
                    <div className="h-12 w-12 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center text-blue-600 dark:text-blue-300">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"></path>
                        <polyline points="10 17 15 12 10 7"></polyline>
                        <line x1="15" y1="12" x2="3" y2="12"></line>
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold">Masuk</h3>
                      <p className="text-muted-foreground">Akses akun yang sudah ada</p>
                    </div>
                  </div>
                </Link>
                
                <Link href="/account/register" className="auth-option-card block p-6 rounded-xl border border-purple-200 bg-purple-50 hover:shadow-md transition-all hover:-translate-y-1">
                  <div className="flex items-center gap-4">
                    <div className="h-12 w-12 rounded-full bg-purple-100 dark:bg-purple-900 flex items-center justify-center text-purple-600 dark:text-purple-300">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="8.5" cy="7" r="4"></circle>
                        <line x1="20" y1="8" x2="20" y2="14"></line>
                        <line x1="23" y1="11" x2="17" y2="11"></line>
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold">Daftar</h3>
                      <p className="text-muted-foreground">Buat akun baru</p>
                    </div>
                  </div>
                </Link>
              </div>
              
              <div className="text-center mt-8">
                <Link href="/" className="text-sm text-muted-foreground hover:text-primary flex items-center justify-center gap-1">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M19 12H5M12 19l-7-7 7-7"/>
                  </svg>
                  Kembali ke Beranda
                </Link>
              </div>
            </div>
          ) : (
            children
          )}
        </div>
      </div>
    </div>
      </body>
    </html>
  )
}
