// This would typically come from your database
export const contributors = [
  {
    id: "c1",
    name: "Alex Johnson",
    role: "Lead Analyst",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Professional Mobile Legends coach with over 5 years of experience in the competitive scene. Former coach for top-tier teams in SEA region.",
    contributions: 48,
    specialties: ["Draft Analysis", "Meta Trends", "Team Strategy"],
    social: {
      twitter: "https://twitter.com",
      github: "https://github.com",
      linkedin: "https://linkedin.com",
      website: "https://example.com",
    },
  },
  {
    id: "c2",
    name: "Sarah Chen",
    role: "Data Analyst",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Data scientist specializing in esports analytics. Developed statistical models for predicting match outcomes and player performance.",
    contributions: 36,
    specialties: [
      "Statistical Analysis",
      "Performance Metrics",
      "Predictive Models",
    ],
    social: {
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "c3",
    name: "Miguel Rodriguez",
    role: "Content Creator",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Professional content creator and streamer with a focus on Mobile Legends. Creates in-depth video analyses and tutorials.",
    contributions: 29,
    specialties: ["Video Analysis", "Hero Guides", "Tutorial Content"],
    social: {
      twitter: "https://twitter.com",
      github: "https://github.com",
      website: "https://example.com",
    },
  },
  {
    id: "c4",
    name: "Aisha Patel",
    role: "Pro Player",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Former professional Mobile Legends player with experience in international tournaments. Now focuses on sharing insights and analysis.",
    contributions: 22,
    specialties: ["Pro Perspective", "Gameplay Analysis", "Hero Mastery"],
    social: {
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "c5",
    name: "David Kim",
    role: "Tournament Analyst",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Specializes in tournament coverage and analysis. Has covered major Mobile Legends events including M-series World Championships.",
    contributions: 18,
    specialties: ["Tournament Coverage", "Team Profiles", "Match Predictions"],
    social: {
      twitter: "https://twitter.com",
      github: "https://github.com",
      linkedin: "https://linkedin.com",
    },
  },
  {
    id: "c6",
    name: "Emma Wilson",
    role: "Community Manager",
    image: "/placeholder.svg?height=200&width=200",
    bio: "Manages community engagement and content curation. Ensures quality and accuracy of analyses published on the platform.",
    contributions: 15,
    specialties: ["Community Building", "Content Curation", "User Engagement"],
    social: {
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
      website: "https://example.com",
    },
  },
];
